package model.common.serviceinterface;

import javax.jws.WebMethod;
import javax.jws.soap.SOAPBinding;

import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
import oracle.webservices.annotations.SDODatabinding;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 18 02:11:25 EEST 2017
// ---------------------------------------------------------------------
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.DOCUMENT)
@PortableWebService(targetNamespace = "/model/common/", name = "AppModuleService",
                    wsdlLocation = "model/common/serviceinterface/AppModuleService.wsdl")
@SDODatabinding(schemaLocation = "model/common/serviceinterface/AppModuleService.xsd")
public interface AppModuleService {
    public static final String NAME = "{/model/common/}AppModuleService";

    /**
     * Exported method DelereAllEMPL from AppModule.
     */
    @WebMethod(action = "/model/common/DelereAllEMPL", operationName = "DelereAllEMPL")
    @RequestWrapper(targetNamespace = "/model/common/types/", localName = "DelereAllEMPL")
    @ResponseWrapper(targetNamespace = "/model/common/types/", localName = "DelereAllEMPLResponse")
    void DelereAllEMPL() throws ServiceException;
}

