package com.ua.model;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 27 13:14:28 EEST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for EmployeesView1.
     * @return EmployeesView1
     */
    public EmployeesViewImpl getEmployeesView1() {
        return (EmployeesViewImpl) findViewObject("EmployeesView1");
    }

    /**
     * Container's getter for EmployeesView2.
     * @return EmployeesView2
     */
    public EmployeesViewImpl getEmployeesView2() {
        return (EmployeesViewImpl) findViewObject("EmployeesView2");
    }

    /**
     * Container's getter for EmployeesView3.
     * @return EmployeesView3
     */
    public EmployeesViewImpl getEmployeesView3() {
        return (EmployeesViewImpl) findViewObject("EmployeesView3");
    }   

    /**
     * Container's getter for EmpManagerFkLink1.
     * @return EmpManagerFkLink1
     */
    public ViewLinkImpl getEmpManagerFkLink1() {
        return (ViewLinkImpl) findViewLink("EmpManagerFkLink1");
    }
    
    public boolean createNewRow(EmployeePojo myEmpl){
        
        try {
            String voDefFile = "com.ua.model.EmployeesView";
            
            String voName = "EmployeesView3";
            ViewObject vo = createViewObject(voName, voDefFile);
            ViewObjectImpl demo;
            demo = (ViewObjectImpl)vo;
            Row r;
            r = demo.createRow();
            r.setAttribute("LastName",myEmpl.getLastName());
            demo.insertRow(r);

            this.getDBTransaction().commit();
            demo.executeQuery();
            return true;
        } catch (Exception e) {
            // TODO: Add catch code
            e.printStackTrace();
        }
        return false;
        
    }
}

