package model;


import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 18 02:00:30 EEST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }
    
    public void makeVO(String str){
        ViewObject vo = this.findViewObject("ViewOdject1");
        vo.remove();
        vo = this.createViewObjectFromQueryStmt("ViewOdject1", "SELECT * FROM employees where first_name like '"+ str +
                                                               "%'"+" or last_name like "+"'"+ str +"%' ");
        vo.executeQuery();

    }

    public void DelereAllEMPL(){
        ViewObject vo = this.findViewObject("Employees1");
        vo.executeQuery();
        //TODO delete of emloyees
    }

    /**
     * Container's getter for DepartmentsView1.
     * @return DepartmentsView1
     */
    public ViewObjectImpl getDepartmentsView1() {
        return (ViewObjectImpl) findViewObject("DepartmentsView1");
    }

    /**
     * Container's getter for EmployeesView1.
     * @return EmployeesView1
     */
    public ViewObjectImpl getEmployeesView1() {
        return (ViewObjectImpl) findViewObject("EmployeesView1");
    }

    /**
     * Container's getter for JobsView1.
     * @return JobsView1
     */
    public ViewObjectImpl getJobsView1() {
        return (ViewObjectImpl) findViewObject("JobsView1");
    }

    /**
     * Container's getter for EmployeesView2.
     * @return EmployeesView2
     */
    public ViewObjectImpl getEmployeesView2() {
        return (ViewObjectImpl) findViewObject("EmployeesView2");
    }

    /**
     * Container's getter for DepartmentsView2.
     * @return DepartmentsView2
     */
    public ViewObjectImpl getDepartmentsView2() {
        return (ViewObjectImpl) findViewObject("DepartmentsView2");
    }

    /**
     * Container's getter for EmployeesView3.
     * @return EmployeesView3
     */
    public ViewObjectImpl getEmployeesView3() {
        return (ViewObjectImpl) findViewObject("EmployeesView3");
    }

    /**
     * Container's getter for EmployeesView4.
     * @return EmployeesView4
     */
    public ViewObjectImpl getEmployeesView4() {
        return (ViewObjectImpl) findViewObject("EmployeesView4");
    }

    /**
     * Container's getter for HighlyPaydEmployees1.
     * @return HighlyPaydEmployees1
     */
    public HighlyPaydEmployeesImpl getHighlyPaydEmployees1() {
        return (HighlyPaydEmployeesImpl) findViewObject("HighlyPaydEmployees1");
    }

    /**
     * Container's getter for EmpTranslatedViewObj1.
     * @return EmpTranslatedViewObj1
     */
    public ViewObjectImpl getEmpTranslatedViewObj1() {
        return (ViewObjectImpl) findViewObject("EmpTranslatedViewObj1");
    }

    /**
     * Container's getter for JobsView2.
     * @return JobsView2
     */
    public ViewObjectImpl getJobsView2() {
        return (ViewObjectImpl) findViewObject("JobsView2");
    }

    /**
     * Container's getter for EmployeesView5.
     * @return EmployeesView5
     */
    public ViewObjectImpl getEmployeesView5() {
        return (ViewObjectImpl) findViewObject("EmployeesView5");
    }

    /**
     * Container's getter for EmpManagerFkLink1.
     * @return EmpManagerFkLink1
     */
    public ViewLinkImpl getEmpManagerFkLink1() {
        return (ViewLinkImpl) findViewLink("EmpManagerFkLink1");
    }

    /**
     * Container's getter for DeptMgrFkLink1.
     * @return DeptMgrFkLink1
     */
    public ViewLinkImpl getDeptMgrFkLink1() {
        return (ViewLinkImpl) findViewLink("DeptMgrFkLink1");
    }

    /**
     * Container's getter for EmpDeptFkLink1.
     * @return EmpDeptFkLink1
     */
    public ViewLinkImpl getEmpDeptFkLink1() {
        return (ViewLinkImpl) findViewLink("EmpDeptFkLink1");
    }

    /**
     * Container's getter for EmpJobFkLink1.
     * @return EmpJobFkLink1
     */
    public ViewLinkImpl getEmpJobFkLink1() {
        return (ViewLinkImpl) findViewLink("EmpJobFkLink1");
    }

    /**
     * Container's getter for JobsToEmployees.
     * @return JobsToEmployees
     */
    public ViewLinkImpl getJobsToEmployees() {
        return (ViewLinkImpl) findViewLink("JobsToEmployees");
    }

    /**
     * Container's getter for ViewOdject1.
     * @return ViewOdject1
     */
    public ViewOdjectImpl getViewOdject1() {
        return (ViewOdjectImpl) findViewObject("ViewOdject1");
    }
}

