package model;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 18 01:34:04 EEST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HighlyPaydEmployeesImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public HighlyPaydEmployeesImpl() {
    }
}

