package model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 21 23:41:28 EEST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ViewOdjectImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ViewOdjectImpl() {
    }
}

