package model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 21 23:55:04 EEST 2017
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {

    void makeVO(String str);

    void DelereAllEMPL();
}

